%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"
Camera.type: "KannalaBrandt8"
# Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 331.698
Camera1.fy: 331.698
Camera1.cx: 481.056
Camera1.cy: 361.061

Camera1.k1: 0.157667
Camera1.k2: -0.0682685
Camera1.k3: 0.0290879
Camera1.k4: -0.00656932

# Camera resolution
Camera.width: 960
Camera.height: 720

# Camera frames per second
Camera.fps: 60

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from body-frame (imu) to camera
IMU.T_b_c1: !!opencv-matrix
    rows: 4
    cols: 4
    dt: f
# permuted calibration
# perm_mat = np.array([
# [0,0,1,0],
# [1,0,0,0],
# [0,1,0,0],
# [0,0,0,1]
# ])
# mat = perm_mat @ open_cam_imu_tbc
    data: [ -0.999938,    0.0104917,    0.00369779,  -0.000565137,
           -0.00357507,  0.0116917,   -0.999925,    -0.0038079,
           -0.0105341,   -0.999877,   -0.0116534,   -0.0012136,
            0.,           0.,           0.,            1. ]


# IMU noise
IMU.NoiseGyro: 0.0338
IMU.NoiseAcc: 0.1502
IMU.GyroWalk: 5.0e-5
IMU.AccWalk: 0.0055
IMU.Frequency: 197.27

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
# ORBextractor.iniThFAST: 20
# ORBextractor.minThFAST: 7
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 5

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5 # -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0
